server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order-service
          predicates:
            - Path=/api/orders
            - Path=/api/orders/**
        - id: inventory
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
    discovery:
      locator:
        enabled: true

  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  metrics: 
    tags:
      application: gateway
  tracing:
    sampling:
      probability: 1.0


