server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
