server:
  port: 8083

spring:
  kafka:
    bootstrap-servers: kafka:9092
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: notification-service
  tracing:
    sampling:
      probability: 1.0

