server:
  port: 8081

spring:
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: order-service
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      inventoryServiceCB:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 100
  retry:
    instances:
      inventoryServiceCB:
        maxAttempts: 3
        waitDuration: 500ms
